version: "3.9"

services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"     # Event Bus Publish
      - "4443:4443"     # Event Bus Subscribe
      - "4444:4444"     # Selenium Grid UI
    environment:
      - SE_LOG_LEVEL=INFO
    networks:
      - selenium-grid

  chrome:
    image: seleniarm/node-chromium:latest
    container_name: chrome-node
    shm_size: "2g"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-grid

  firefox:
    image: seleniarm/node-firefox:latest
    container_name: firefox-node
    shm_size: "2g"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge